[2023-05-05T06:19:11.786+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Raw_To_Processed_Job.spark_submit_job scheduled__2023-05-04T00:00:00+00:00 [queued]>
[2023-05-05T06:19:11.793+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Raw_To_Processed_Job.spark_submit_job scheduled__2023-05-04T00:00:00+00:00 [queued]>
[2023-05-05T06:19:11.793+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-05T06:19:11.810+0000] {taskinstance.py:1350} INFO - Executing <Task(SparkSubmitOperator): spark_submit_job> on 2023-05-04 00:00:00+00:00
[2023-05-05T06:19:11.814+0000] {standard_task_runner.py:57} INFO - Started process 10843 to run task
[2023-05-05T06:19:11.819+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Raw_To_Processed_Job', 'spark_submit_job', 'scheduled__2023-05-04T00:00:00+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/DAG_Raw_to_processed.py', '--cfg-path', '/tmp/tmp04g4z_k9']
[2023-05-05T06:19:11.821+0000] {standard_task_runner.py:85} INFO - Job 126: Subtask spark_submit_job
[2023-05-05T06:19:11.876+0000] {task_command.py:410} INFO - Running <TaskInstance: Raw_To_Processed_Job.spark_submit_job scheduled__2023-05-04T00:00:00+00:00 [running]> on host sample-challenge.asia-south1-b.c.rt-de-sample-task.internal
[2023-05-05T06:19:11.947+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Raw_To_Processed_Job' AIRFLOW_CTX_TASK_ID='spark_submit_job' AIRFLOW_CTX_EXECUTION_DATE='2023-05-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-04T00:00:00+00:00'
[2023-05-05T06:19:11.953+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2023-05-05T06:19:11.955+0000] {spark_submit.py:339} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.driver.memory=15g --conf spark.executor.memory=40g --name arrow-spark --verbose --queue root.default /home/ebony_maw_0/code/Raw_To_Processed.py
[2023-05-05T06:19:13.162+0000] {spark_submit.py:490} INFO - Using properties file: null
[2023-05-05T06:19:13.258+0000] {spark_submit.py:490} INFO - WARNING: An illegal reflective access operation has occurred
[2023-05-05T06:19:13.258+0000] {spark_submit.py:490} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/ebony_maw_0/.local/lib/python3.9/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.4.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2023-05-05T06:19:13.258+0000] {spark_submit.py:490} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2023-05-05T06:19:13.258+0000] {spark_submit.py:490} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2023-05-05T06:19:13.259+0000] {spark_submit.py:490} INFO - WARNING: All illegal access operations will be denied in a future release
[2023-05-05T06:19:13.328+0000] {spark_submit.py:490} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2023-05-05T06:19:13.328+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:634)
[2023-05-05T06:19:13.328+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:274)
[2023-05-05T06:19:13.329+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:234)
[2023-05-05T06:19:13.329+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:119)
[2023-05-05T06:19:13.329+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1037)
[2023-05-05T06:19:13.329+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1037)
[2023-05-05T06:19:13.329+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
[2023-05-05T06:19:13.330+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1054)
[2023-05-05T06:19:13.330+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1063)
[2023-05-05T06:19:13.330+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2023-05-05T06:19:13.358+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ebony_maw_0/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/ebony_maw_0/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 421, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.driver.memory=15g --conf spark.executor.memory=40g --name arrow-spark --verbose --queue root.default /home/ebony_maw_0/code/Raw_To_Processed.py. Error code is: 1.
[2023-05-05T06:19:13.362+0000] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=Raw_To_Processed_Job, task_id=spark_submit_job, execution_date=20230504T000000, start_date=20230505T061911, end_date=20230505T061913
[2023-05-05T06:19:13.377+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 126 for task spark_submit_job (Cannot execute: spark-submit --master yarn --conf spark.driver.memory=15g --conf spark.executor.memory=40g --name arrow-spark --verbose --queue root.default /home/ebony_maw_0/code/Raw_To_Processed.py. Error code is: 1.; 10843)
[2023-05-05T06:19:13.396+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-05T06:19:13.410+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
